# coding=utf-8

# This will be displayed as the title of the tab, ex "Aeternum"
# will display the title "Aeternum - Project Anima" on the tab
tabtitle = "Chassis"

keywords = "​​​​combat mage, chassis, biomechanical , Paraphysics Division, Research and Technology Sector, Bases, Central Cognition Cores (CCC), General Utility Combat Chassis (GUCC), Soft Systems, Hard Systems, Nanolaminate Plating, Superstructure, Artificial Muscles, liquid-metal matrix, Somatic Threads, mana, psions, Modular Armature System (MAS), Nanite Nodes, nanites, nanopod // nanite pod, Movement Systems, Digitigrade Legs, Power Limbs, Jointed Limbs, Non-Jointed Limbs, Manipular Limbs, artificial cilia, Flight Packages, Njordian Flight Unit, repulsor-type thrusters, Utility Slots, Utility Modules, Central Cognition Core (CCC), mage, Anchor, Computation Module, Sensor and Communications Suite (SCS), mage-to-ship communications,sensory capabilities, magnetoreception, thermography, object bypass vision (OBV) , electroreception, psioreception, drones, mothership, Mana-Catalyzed Micro Antimatter Reactor (MCMAR), wand, hydrogen-antihydrogen reactions, fine manipulation, Auxiliary Life Support (ALS)"

# This is the information that will appear in the lil box on
# the right, the order the entries appear in the box is:
# 1 4
# 2 5
# 3 6
infoheadings = ["CATEGORY", "CREATOR", "CLASS", "SPECIES", "AUTHOR", "LAST UPDATE"]
infoentries = ["Items", "Paraphysics Division", "Robotics", "Human", "Devin Deng", "September 1st, 2021"]

# this is the address of the image that appears in the lil
# box on the right, make sure it's relative to the html file
# (probably something like resources/image.jpg)
infoimagesource = "resources/Chassis Icon.svg"

# if the article has links, put the addresses for those links
# here. They must be listed in the same order as they appear
# in the article. You can omit the .html extension
articlelinks = ['combatmages-lore', 'paraphysicsdivision-lore']

# this is the hardest part so read it carefully, look at the
# example for reference, make sure text is surrounded by triple quotes.
#
# 1 - surround links with brackets, and make sure they correspond
#     the links listed directly above exactly, the text in brackets
#     is what the user clicks on and the link above is where it'll
#     redirect
#
# 2 - be conscious of newlines, they're used to separate paragraphs
#     and heading and such but be aware that something like two
#     consecutive newlines will be interpreted as an extra space
#
# 3 - three equal signs at the beginning of a line signifies a
#     large title that you probably only need at the very
#     beginning of the article, make sure the rest is in all caps
#
# 4 - two equal signs at the beginning of a line signifies a
#     section title, make sure the rest of the line is all caps
#
# 5 - one equal sign at the beginning of a line signifies a
#     paragraph title, the rest should be capitalized regularly
#
# 6 - any line that doesn't start with equal signs is interpreted
#     as a regular paragraph

article = """===CHASSIS
A {combat mage}’s chassis is its body and its method of interaction with the environment. The chassis is a biomechanical frame that is composed of the most advanced materials produced by the {Paraphysics Division}. New versions of chassis are always being generated by the designer AI of the Research and Technology Sector.
==BASES
Bases are biomechanical bodies that Central Cognition Cores (CCC) can be inserted into. These CCC’s can adapt to suit special situations, but the most commonly used version is the General Utility Combat Chassis (GUCC).
=Hard Systems
_Nanolaminate Plating and Superstructure
The material used to form the outer shell and superstructure is known as nanolaminate. Nanolaminate is composed of micron-scale layers of varying elements and compounds. These layers are placed on top of each other in different orientations to induce different properties while also accomplishing high density. These layers can be modified to induce thermal resistance, thermal dispersion, impact toughness, malleability, and other properties.
_Artificial Muscles
The current generation of chassis utilizes an artificial muscular system that is composed of a liquid-metal matrix which changes its structure based on the level of electrical charge. This allows for remarkable flexibility and strength in an incredibly small volume.
=Soft Systems
_Somatic Threads
A combat mage’s somatic threads are a four-bundled system of wires that transfer mana, psions, data, and power throughout the chassis. The threads are especially thin and have the ability to extrude out of specific orifices in a chassis so a combat mage can interface with certain technologies.
==MODULAR ARMATURE SYSTEM (MAS)
The MAS is an essential part of most chassis. They allow for a single base to be adapted to a multitude of mission profiles.
=Nanite Nodes
Nanite nodes are extrusion points where nanites can exit the nanopod to execute tasks. They are incredibly small and are two-fold hermetically sealed.
=Digitigrade Legs
For increased agility and mobility, the digitigrade leg option is available. To compensate for the inherent shortcomings of digitigrade legs, there is the option of adding support pads that increase the surface area of the foot. The feet of these legs are also inherently modular, allowing them to form any sort of underfoot from snowshoes to noise-dampening padding.
=Power Limbs
Power limbs are stronger than Manipular limbs, but lack the manipular limbs’ precision. They can be categorized into two subtypes:
_Jointed Limbs
While greater in strength than non-jointed limbs, they are weaker in terms of flexibility.
_Non-Jointed Limbs
While stronger in flexibility than jointed limbs, they are weaker in terms of strength.
=Manipular Limbs
Manipular limbs are weak yet nimble compared to their power limb counterparts. They are covered in nanite nodes to allow nanites to form the best complement of whatever the limb needs to interface with. This creates artificial cilia that allow for manipulation on a microscopic level. Manipulars can also come equipped with a series of tech interface fingers, allowing combat mages to physically tap into a large number of electronic and mechanical systems.
=Flight Packages
Flight packages allow the combat mage to achieve flight. The most popular is the Njordian Flight Unit, a series of repulsor-type thrusters mounted on flexible limbs for maximum agility while in the air.
==UTILITY SLOTS
Utility slots and their complementary utility modules are the primary functional components of a combat mage’s chassis.
=Central Cognition Core (CCC)
The CCC is the main brain of any mage. It is where the anchor resides, and thus where mana and psions are generated. As a result, the psionic threads are linked directly to this unit. The CCC and the computation module have the option of being ex-situ but at the cost of response speeds and increased latency.
=Computation Module
Computation modules host maintenance subsystems as well as the assistant AI.
=Sensor and Communications Suite (SCS)
The SCS allows access to not only mage-to-ship communications but also affords the combat mage a series of sensory capabilities. On top of heightened baseline senses (sight, smell, touch, taste, and hearing), SCS’s are afforded a series of other senses depending on the sensory package. These other senses include, but are not limited to magnetoreception, thermography, object bypass vision (OBV), electroreception, and psioreception. Drones with additional points of view, as well as the mothership, can provide additional sensory data and improve situational awareness.
=Mana-Catalyzed Micro Antimatter Reactor (MCMAR)
The MCMAR is a modular portable power supply that fuels both the combat mage’s chassis and wand. The MCMAR utilizes hydrogen-antihydrogen reactions to ensure that combat mages and their weapons are capable of operating unassisted for years on end.
=Nanite Pod (Nanopod)
A nanite pod contains a single swarm of nanites. These nanites could be used for a variety of tasks such as machine interfacing, fine manipulation, and temporary repair.
=Auxiliary Life Support (ALS)
In extreme cases, the CCC can be ejected and supported by the ALS until retrieval by extraction teams. """

# this is the file the html gets saved in, make sure to include
# the .html extension
filename = "chassis-lore.html"

# ignore this stuff
article = article.replace('{', "<a class='infolink' href='(LINKGOESHERE)'>")
article = article.replace('}', "</a>")
for link in articlelinks:
	article = article.replace('(LINKGOESHERE)', link, 1)

htmlcode = ""
lines = article.split('\n')
for line in lines:
	if len(line)>=3 and line[:3]=='===':
		curID = line[3:].lower().replace(' ', '-')
		htmlcode += "\t\t<h1 id='"+curID+"'>" + line[3:] + "</h1>\n\t\t<span class='underline1'></span>\n"
	elif len(line)>=2 and line[:2]=='==':
		curID = line[2:].lower().replace(' ', '-')
		htmlcode += "\t\t<h2 id='"+curID+"'>" + line[2:] + "</h2>\n\t\t<span class='underline2'></span>\n"
	elif len(line)>=1 and line[:1]=='=':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h3 id='"+curID+"'>" + line[1:] + "</h3>\n"
	elif len(line)>=1 and line[:1]=='_':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h4 id='"+curID+"'>" + line[1:] + "</h4>\n"
	else:
		htmlcode += "\t\t<p class='infoparagraph'>" + line + "</p>\n"

s = open('loretemplate.txt', 'r').read()
s = s.replace('(PAGETITLE)', tabtitle)
s = s.replace('(INFOIMAGE)', infoimagesource)
s = s.replace('(KEYWORDS)', keywords)
for i in range(6):
	s = s.replace('(H'+str(i)+')', infoheadings[i])
	s = s.replace('(I'+str(i)+')', infoentries[i])
s = s.replace('(CONTENT)', htmlcode)

f = open(filename, 'w')
f.write(s)
f.close()
