# coding=utf-8

# This will be displayed as the title of the tab, ex "Aeternum"
# will display the title "Aeternum - Project Anima" on the tab
tabtitle = "Argentimaria Attack"

keywords = "​​​​Argentimaria Attack, BCI-based psychotechnical terrorist attack, lunar city, Argentimaria, seventh of November, anti-BCI group, Ad Antea, Neurogenesis, BCI firm, neurovirus attack, backdoor, guardian AI, data traffic, malignant information, trojan virus, nervous system, motor control, live capture footage, rogue craft, atmospheric dome, analyst AI, Terran Union, Foxhound, anti-terrorism division, Terran military, trial and punishment, Eris, Sol System, thaumaturgists, orbital facilities, chronoprison, Union government, Human Domain"

# This is the information that will appear in the lil box on
# the right, the order the entries appear in the box is:
# 1 4
# 2 5
# 3 6
infoheadings = ["CATEGORY", "LOCATION", "CLASS", "PERPETRATOR", "AUTHOR", "LAST UPDATE"]
infoentries = ["History", "Argentimaria", "Terrorist Act", "Ad Antea", "Devin Deng", "September 1st, 2021"]

# this is the address of the image that appears in the lil
# box on the right, make sure it's relative to the html file
# (probably something like resources/image.jpg)
infoimagesource = "resources/Argentimaria Attack Icon.svg"

# if the article has links, put the addresses for those links
# here. They must be listed in the same order as they appear
# in the article. You can omit the .html extension
articlelinks = []

# this is the hardest part so read it carefully, look at the
# example for reference, make sure text is surrounded by triple quotes.
#
# 1 - surround links with brackets, and make sure they correspond
#     the links listed directly above exactly, the text in brackets
#     is what the user clicks on and the link above is where it'll
#     redirect
#
# 2 - be conscious of newlines, they're used to separate paragraphs
#     and heading and such but be aware that something like two
#     consecutive newlines will be interpreted as an extra space
#
# 3 - three equal signs at the beginning of a line signifies a
#     large title that you probably only need at the very
#     beginning of the article, make sure the rest is in all caps
#
# 4 - two equal signs at the beginning of a line signifies a
#     section title, make sure the rest of the line is all caps
#
# 5 - one equal sign at the beginning of a line signifies a
#     paragraph title, the rest should be capitalized regularly
#
# 6 - any line that doesn't start with equal signs is interpreted
#     as a regular paragraph

article = """===ARGENTIMARIA ATTACK
The Argentimaria Attack was a BCI-based psychotechnical terrorist attack that took place in the lunar city of Argentimaria. On the seventh of November, 2133, a fanatical anti-BCI group known as Ad Antea penetrated the servers of Neurogenesis, a popular BCI firm at the time, and instigated a neurovirus attack through a backdoor. While many people who owned BCIs had guardian AI to help sift through data traffic and remove potentially malignant information, a specifically tailored trojan virus was generated by Ad Antea for this operation. The deployment of this virus allowed Ad Antea a strong degree of control over people’s nervous system, more importantly their motor control.
The ensuing chaos was seen through live capture footage, showing people tearing themselves apart while fully conscious, children jumping off the roofs of buildings, and others simply standing perfectly still staring at the sun. Even the animals were not spared, with security footage showing owners getting eaten alive by their own beloved pets. A rogue craft crashed into the side of the atmospheric dome, causing a large rupture that sucked out more than a hundred people before being sealed by expanding foam. It took Neurogenesis an entire sixteen minutes to realize the issue and stop the data streams, but in that short time frame the damage was already done. More than five thousand people were killed and tens of thousands more were injured.
After the attack, analyst AI of the Terran Union quickly determined that Ad Antea was behind the attack. Foxhound, an anti-terrorism division of the Terran military. was tasked to find Ad Antea and bring in the perpetrators for trial and imprisonment. Several days of investigation found that the signal used to begin the attack originated from Eris in the Sol System. Foxhound thaumaturgists were deployed and held the orbital facilities of Eris under lockdown. The perpetrators were caught and were each sentenced to twelve centuries in a chronoprison.
The aftereffects of the Argentimaria Attack were widespread. Neurogenesis was held accountable for failing to prevent the tragedy, with the company being disbanded a few weeks later. Newer, stricter regulations were drawn up by the Union government concerning the administration and application of brain-computer interfaces. Many people within the Human Domain lost faith in BCIs for a while, causing a recession in the BCI sector of the market. After the city of Argentimaria was repaired and the bodies buried, a memorial was established where on the seventh of every November, leaders of the Terran Union would visit to honor those that had suffered."""

# this is the file the html gets saved in, make sure to include
# the .html extension
filename = "argentimariaattack-lore.html"

# ignore this stuff
article = article.replace('{', "<a class='infolink' href='(LINKGOESHERE)'>")
article = article.replace('}', "</a>")
for link in articlelinks:
	article = article.replace('(LINKGOESHERE)', link, 1)

htmlcode = ""
lines = article.split('\n')
for line in lines:
	if len(line)>=3 and line[:3]=='===':
		curID = line[3:].lower().replace(' ', '-')
		htmlcode += "\t\t<h1 id='"+curID+"'>" + line[3:] + "</h1>\n\t\t<span class='underline1'></span>\n"
	elif len(line)>=2 and line[:2]=='==':
		curID = line[2:].lower().replace(' ', '-')
		htmlcode += "\t\t<h2 id='"+curID+"'>" + line[2:] + "</h2>\n\t\t<span class='underline2'></span>\n"
	elif len(line)>=1 and line[:1]=='=':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h3 id='"+curID+"'>" + line[1:] + "</h3>\n"
	elif len(line)>=1 and line[:1]=='_':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h4 id='"+curID+"'>" + line[1:] + "</h4>\n"
	else:
		htmlcode += "\t\t<p class='infoparagraph'>" + line + "</p>\n"

s = open('loretemplate.txt', 'r').read()
s = s.replace('(PAGETITLE)', tabtitle)
s = s.replace('(INFOIMAGE)', infoimagesource)
s = s.replace('(KEYWORDS)', keywords)
for i in range(6):
	s = s.replace('(H'+str(i)+')', infoheadings[i])
	s = s.replace('(I'+str(i)+')', infoentries[i])
s = s.replace('(CONTENT)', htmlcode)

f = open(filename, 'w')
f.write(s)
f.close()
