# coding=utf-8

# This will be displayed as the title of the tab, ex "Aeternum"
# will display the title "Aeternum - Project Anima" on the tab
tabtitle = "Ego"

keywords = "​​​​souls, liturgy, Ego, Ixus, Theomachy, Zaehaldyn (the Mortal Instrument), Eyon, Aunox, True Form, metaphysics, Apotheon, Perfect Shapes, Abyss, Voidslash, Slab of Time, Sisyphean Scribe, Vagabond Artificers"

# This is the information that will appear in the lil box on
# the right, the order the entries appear in the box is:
# 1 4
# 2 5
# 3 6
infoheadings = ["CATEGORY", "DOMAIN", "CLASS", "SPECIES", "AUTHOR", "LAST UPDATE"]
infoentries = ["Factions", "Mixed", "Construct", "Ego", "Devin Deng", "September 1st, 2021"]

# this is the address of the image that appears in the lil
# box on the right, make sure it's relative to the html file
# (probably something like resources/image.jpg)
infoimagesource = "resources/Ego Icon.svg"

# if the article has links, put the addresses for those links
# here. They must be listed in the same order as they appear
# in the article. You can omit the .html extension
articlelinks = []

# this is the hardest part so read it carefully, look at the
# example for reference, make sure text is surrounded by triple quotes.
#
# 1 - surround links with brackets, and make sure they correspond
#     the links listed directly above exactly, the text in brackets
#     is what the user clicks on and the link above is where it'll
#     redirect
#
# 2 - be conscious of newlines, they're used to separate paragraphs
#     and heading and such but be aware that something like two
#     consecutive newlines will be interpreted as an extra space
#
# 3 - three equal signs at the beginning of a line signifies a
#     large title that you probably only need at the very
#     beginning of the article, make sure the rest is in all caps
#
# 4 - two equal signs at the beginning of a line signifies a
#     section title, make sure the rest of the line is all caps
#
# 5 - one equal sign at the beginning of a line signifies a
#     paragraph title, the rest should be capitalized regularly
#
# 6 - any line that doesn't start with equal signs is interpreted
#     as a regular paragraph

article = """===EGO
Souls can arise from a variety of patterns and phenomena. Whether they be the electrical interactions between neurons or the optical processing fluctuations of an AI, the physical mainframe is the critical factor needed to sustain a liturgy. However, a race known as the Ego seems to defy this universal law, exhibiting souls without possessing the conventional apparati. They were created by Ixus the Logosmith before the Theomachy, but after Ixus’s death, the means of their manufacturing were lost.
==CREATION AND THEORY
Ixus possesses the power to ontologically insert addendums to the precepts of the universe. Extensive experimentation and research in this field by Ixus has allowed it to develop constructs known as Ego, entities whose souls are generated by artificial liturgies. Each ego is bound by different laws and liturgies, meaning they need different processes to sustain themselves. Processes include, but are not limited to, a simple ritual such as drinking from a specific well every day or being forced to slay a soul every time it is unsheathed. They are incapable of breaking these binding tenets, for it is their inherent nature. Many of these entities have been lost or destroyed, with only a scant few surviving to the present day.
==KNOWN EGO
=Zaehaldyn, the Mortal Instrument
Zaehaldyn, the Mortal Instrument, is an ontological weapon forged during the Theomachy for use by Eyon against Aunox. While its base form is matrixed infinities, it can morph into any shape and size desired by its wielder. This form is the platonic form, otherwise known as the True Form, of whatever it represents. This empowers Zaehaldyn on a metaphysical level, turning it into an Apotheon of the specific weapon. These forms are changing constantly due to the meanings of the weapons. However, becoming Perfect Shapes is not its primary ability. Due to it being forged in the Abyss and being pushed into the Universe, the Mortal Instrument’s main ability is being able to channel the ontological abilities of Eyon, meaning Zaehaldyn is one of the only objects in Existence that can channel and amplify Eyon’s “Voidslash” perfectly.
=The Slab of Time and the Sisyphean Scribe
The Slab of Time is a layered slab inscribed with text of unknown origin and meaning. It is built and written on by an entity known as the Sisyphean Scribe. This process begins with the Scribe venturing out into the unknown to search for a suitable asteroid or celestial body. Once it has found one to its liking, it will tug the body to the slab, proceeding to meld and reshape the material to the shape of the slab. The Sisyphean Scribe will then arm itself with a hammer and chisel of its own creation, and cut a seemingly random assortment of glyphs and characters into the newly added portion of the slab. Many pilgrims that travel to the structure and observe the texts believe them to be sibylline in nature, but those who knew Ixus before its death surmise the writings to simply be gibberish. It could be noted that the Sisyphean Scribe ignores almost everything in its surroundings, seeming to only be focused on its task. However, it will respond to attacks targeting itself or its slab with great hostility, using its hammer and chisel to kill vandalizers and defacers.
=Vagabond Artificers
The Vagabond Artificers are fragments of Ixus forged into beings of creation. They resemble amorphous slimes, swallowing raw materials and processing them into products. From weapons repair to logosmithing, they possess an instinctual ability to craft anything that is desired of them. When Ixus died, their minds were shattered, severely diminishing their creative and cognitive abilities. Now, they roam the galaxy in a seeming trance, fixing or creating products at random.
"""

# this is the file the html gets saved in, make sure to include
# the .html extension
filename = "ego-lore.html"

# ignore this stuff
article = article.replace('{', "<a class='infolink' href='(LINKGOESHERE)'>")
article = article.replace('}', "</a>")
for link in articlelinks:
	article = article.replace('(LINKGOESHERE)', link, 1)

htmlcode = ""
lines = article.split('\n')
for line in lines:
	if len(line)>=3 and line[:3]=='===':
		curID = line[3:].lower().replace(' ', '-')
		htmlcode += "\t\t<h1 id='"+curID+"'>" + line[3:] + "</h1>\n\t\t<span class='underline1'></span>\n"
	elif len(line)>=2 and line[:2]=='==':
		curID = line[2:].lower().replace(' ', '-')
		htmlcode += "\t\t<h2 id='"+curID+"'>" + line[2:] + "</h2>\n\t\t<span class='underline2'></span>\n"
	elif len(line)>=1 and line[:1]=='=':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h3 id='"+curID+"'>" + line[1:] + "</h3>\n"
	elif len(line)>=1 and line[:1]=='_':
		curID = line[1:].lower().replace(' ', '-')
		htmlcode += "\t\t<h4 id='"+curID+"'>" + line[1:] + "</h4>\n"
	else:
		htmlcode += "\t\t<p class='infoparagraph'>" + line + "</p>\n"

s = open('loretemplate.txt', 'r').read()
s = s.replace('(PAGETITLE)', tabtitle)
s = s.replace('(INFOIMAGE)', infoimagesource)
s = s.replace('(KEYWORDS)', keywords)
for i in range(6):
	s = s.replace('(H'+str(i)+')', infoheadings[i])
	s = s.replace('(I'+str(i)+')', infoentries[i])
s = s.replace('(CONTENT)', htmlcode)

f = open(filename, 'w')
f.write(s)
f.close()
